apiVersion: apps/v1
kind: Deployment
metadata:
  name: fantaco-customer-main
  labels:
    app: fantaco-customer-main
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fantaco-customer-main
  template:
    metadata:
      labels:
        app: fantaco-customer-main
    spec:
      containers:
      - name: fantaco-customer-main
        image: quay.io/burrsutter/fantaco-customer-main:1.0.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        env:
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: fantaco-customer-config
              key: database.url
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            configMapKeyRef:
              name: fantaco-customer-config
              key: database.username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: fantaco-customer-secret
              key: database.password
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 256Mi
